title: This is the title
author: Author Name
date: today
project:
  type: default
  output-dir: publish
  render:
    - index.qmd
number-sections: true
link-citations: true

format:
  pdf:
    include-in-header:
      - custom.tex
    indent: true
    cite-method: biblatex
    biblio-title: 参考文献
    bibliography: bibliography.bib
    keep-tex: true
