title: This is the title
author: Author Name
date: today
project:
  type: default
  output-dir: publish
  render:
    - index.qmd
number-sections: true
link-citations: true

format:
  pdf:
    include-in-header:
      - custom.tex
